### ISSUE TITLE
utils.PyconvResNet

### ISSUE THREAD

**Issue by chiukin** [wuzhenyubuaa/DPNet#1]
你上传的utils里没有PyconvResNet这个文件。另外想问下，使用的bk是来自 Pyramidal Convolution: Rethinking Convolutional Neural Networks for Visual Recognition 提出的吗，还是你们新设计的呢?

**Comment by john-zys** [comment]
这个backbone应该是他们自己做的，但是问什么不公布backbone部分的代码呢？

**Comment by chiukin** [comment]
代码不全，他把训练权重放出来也没用，运行不了，无法验证

**Comment by Vincent630** [comment]
不想开源或者不能开源可以不开，这又何必？
